CREATE TABLE [dbo].[PatientRegistration]
(
    [PatientId]              UNIQUEIDENTIFIER   NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [DateOfVisit]            DATE               NOT NULL,
    [TimeOfVisit]            TIME               NOT NULL,
    [ComingFrom]             VARCHAR(100)       NULL,
    [Reference]              VARCHAR(100)       NULL,
    [PatientName]            VARCHAR(150)       NOT NULL,
    [PhoneNo]                VARCHAR(15)        NOT NULL,
    [AlternatePhoneNo]       VARCHAR(15)        NULL,
    [Email]                  VARCHAR(100)       NULL,
    [Gender]                 VARCHAR(10)        NOT NULL,
    [DOB]                    DATE               NOT NULL,
    [Height]                 FLOAT              NULL,
    [Weight]                 FLOAT              NULL,
    [BP]                     VARCHAR(10)        NULL,
    [Sugar]                  FLOAT              NULL,
    [Temperature]            FLOAT              NULL,
    [HealthIssues]           TEXT               NULL,
    [DoctorAssignedId]       UNIQUEIDENTIFIER                NOT NULL,
    [Fee]                    DECIMAL(10, 2)     NOT NULL,
    [PreparedBy]             VARCHAR(100)       NULL,
    [CreatedBy]              UNIQUEIDENTIFIER   NULL,
    [CreatedOn]              DATETIMEOFFSET     DEFAULT SYSDATETIMEOFFSET(),
    [ModifiedBy]             UNIQUEIDENTIFIER   NULL,
    [ModifiedOn]             DATETIMEOFFSET     NULL,
    [IsActive]               BIT                DEFAULT 1,
    FOREIGN KEY (DoctorAssignedId) REFERENCES [dbo].[DoctorAssignment](AssignmentId)
);